package ru.redenergy.warden.entity

import com.j256.ormlite.field.DatabaseField as db
import com.j256.ormlite.table.DatabaseTable
import java.sql.Timestamp

/**
 * Represents total online in one moment
 *
 * @constructor
 * @param id - primary id, normally is generated by ormlite
 * @param time - timestamp
 * @param online - total number of players
 */
@DatabaseTable(tableName = "total")
class TotalOnline(@com.j256.ormlite.field.DatabaseField(generatedId = true) val id: Int = -1, @com.j256.ormlite.field.DatabaseField val time: Timestamp, @com.j256.ormlite.field.DatabaseField val online: Int){

    //for ormlite
    constructor(): this(time = Timestamp(0), online = -1)
}